"use strict";

/*
  Hardcoded-secret detection rules.

  Source: https://github.com/streaak/keyhacks (patterns supplied and verified
  by the user). Each rule is { name, pattern }; patterns are matched against
  the reconstructed sourcesContent of each discovered source map. Flags are
  preserved exactly as provided.

  Chrome port note: this module is identical to the Firefox original — it is
  pure data with no WebExtension API calls, so it ports unchanged.
*/

(function exposeSecretRules() {
  const RULES = [
    { name: "ABTasty API Key", pattern: /["']?abtasty["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Algolia App ID", pattern: /["']?algolia[_\-]?app[_\-]?id["']?\s*[:=]\s*["']?([A-Z0-9]{10})["']?/i },
    { name: "Algolia API Key", pattern: /["']?algolia[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Amplitude API Key", pattern: /["']?amplitude[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Asana Access Token", pattern: /["']?asana[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?(\d+\/[0-9a-f]{32})["']?/i },
    { name: "AWS Access Key ID", pattern: /\b(AKIA[0-9A-Z]{16})\b/ },
    { name: "AWS Secret Access Key", pattern: /["']?aws[_\-]?secret[_\-]?(?:access[_\-]?)?key["']?\s*[:=]\s*["']?([A-Za-z0-9\/+]{40})["']?/i },
    { name: "Azure App Insights App ID", pattern: /["']?(?:appid|app[_\-]?id)["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "Azure App Insights API Key", pattern: /["']?(?:azure|appinsights)[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-z0-9]{22})["']?/i },
    { name: "Bazaarvoice Passkey", pattern: /["']?(?:bv[_\-]?)?passkey["']?\s*[:=]\s*["']?([a-zA-Z0-9]{32,64})["']?/i },
    { name: "Bing Maps API Key", pattern: /["']?bing[_\-]?(?:maps[_\-]?)?(?:api[_\-]?)?key["']?\s*[:=]\s*["']?([A-Za-z0-9_\-]{43,90})["']?/i },
    { name: "Bit.ly Access Token", pattern: /["']?bit\.?ly[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{40}|[A-Za-z0-9_\-]{30,50})["']?/i },
    { name: "Branch.io Key", pattern: /\b(key_live_[a-zA-Z0-9]{32})\b/ },
    { name: "Branch.io Secret", pattern: /\b(secret_live_[a-zA-Z0-9]{32})\b/ },
    { name: "Buildkite Access Token", pattern: /["']?buildkite[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?([a-zA-Z0-9_\-]{20,40})["']?/i },
    { name: "ButterCMS API Key", pattern: /["']?butter(?:cms)?[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-z0-9]{40})["']?/i },
    { name: "Calendly API Key", pattern: /["']?calendly[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-zA-Z0-9_\-]{30,60})["']?/i },
    { name: "CircleCI Access Token", pattern: /["']?circle(?:ci)?[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "Cloudflare API Key", pattern: /["']?cloudflare[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([0-9a-f]{37})["']?/i },
    { name: "Cloudflare API Token", pattern: /["']?cloudflare[_\-]?api[_\-]?token["']?\s*[:=]\s*["']?([A-Za-z0-9_\-]{40})["']?/i },
    { name: "Contentful Access Token", pattern: /["']?contentful[_\-]?(?:access[_\-]?|delivery[_\-]?|preview[_\-]?)?token["']?\s*[:=]\s*["']?([a-zA-Z0-9_\-]{43,64})["']?/i },
    { name: "Cypress Record Key", pattern: /["']?cypress[_\-]?record[_\-]?key["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "DataDog API Key", pattern: /["']?datadog[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "DataDog App Key", pattern: /["']?datadog[_\-]?app[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "Delighted API Key", pattern: /["']?delighted[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-zA-Z0-9]{20,40})["']?/i },
    { name: "Deviant Art Access Token", pattern: /["']?deviantart[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?([a-zA-Z0-9]{32,64})["']?/i },
    { name: "Deviant Art Secret", pattern: /["']?deviantart[_\-]?(?:client[_\-]?)?secret["']?\s*[:=]\s*["']?([a-zA-Z0-9]{32,64})["']?/i },
    { name: "Dropbox API Token", pattern: /\b(sl\.[A-Za-z0-9_\-]{130,145})\b/ },
    { name: "Facebook Access Token", pattern: /\b(EAA[A-Za-z0-9]{100,})\b/ },
    { name: "Facebook App Secret", pattern: /["']?(?:facebook|fb)[_\-]?(?:app[_\-]?)?secret["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Firebase / Google API Key", pattern: /\b(AIza[0-9A-Za-z\-_]{35})\b/ },
    { name: "FCM Server Key", pattern: /\b(AAAA[A-Za-z0-9_\-]{7}:[A-Za-z0-9_\-]{140})\b/ },
    { name: "FreshDesk API Key", pattern: /["']?freshdesk[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-zA-Z0-9]{20,40})["']?/i },
    { name: "GitHub Client ID", pattern: /["']?github[_\-]?client[_\-]?id["']?\s*[:=]\s*["']?([0-9a-f]{20})["']?/i },
    { name: "GitHub Client Secret", pattern: /["']?github[_\-]?client[_\-]?secret["']?\s*[:=]\s*["']?([0-9a-f]{40})["']?/i },
    { name: "GitHub Token (new)", pattern: /\b(gh[pousr]_[A-Za-z0-9]{36,255})\b/ },
    { name: "GitHub Token (old)", pattern: /["']?github[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "GitLab Personal Access Token", pattern: /\b(glpat-[A-Za-z0-9_\-]{20,})\b/ },
    { name: "GitLab Runner Registration Token", pattern: /\b(GR1348941[A-Za-z0-9_\-]{20})\b/ },
    { name: "Google Cloud Service Account", pattern: /"type"\s*:\s*"service_account"/ },
    { name: "Google reCAPTCHA Key", pattern: /\b(6L[0-9a-zA-Z_\-]{38})\b/ },
    { name: "Grafana API Token", pattern: /["']?grafana[_\-]?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?(eyJ[A-Za-z0-9_\-\.]+)["']?/i },
    { name: "Help Scout OAuth Token", pattern: /["']?helpscout[_\-]?(?:oauth[_\-]?|access[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{64})["']?/i },
    { name: "Heroku API Key", pattern: /["']?heroku[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "HubSpot API Key", pattern: /["']?hubspot[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "Infura API Key", pattern: /["']?infura[_\-]?(?:project[_\-]?)?(?:id|key|secret)["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Instagram Access Token", pattern: /\b(IGQ[A-Za-z0-9_\-]{100,})\b/ },
    { name: "Ipstack API Key", pattern: /["']?ipstack[_\-]?(?:api[_\-]?)?(?:key|token)["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Iterable API Key", pattern: /["']?iterable[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-zA-Z0-9]{30,40})["']?/i },
    { name: "JumpCloud API Key", pattern: /["']?jumpcloud[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "Keen.io API Key", pattern: /["']?keen(?:io)?[_\-]?(?:api[_\-]?)?(?:write|read)?[_\-]?key["']?\s*[:=]\s*["']?([a-f0-9]{64})["']?/i },
    { name: "LinkedIn Client ID", pattern: /["']?linkedin[_\-]?client[_\-]?id["']?\s*[:=]\s*["']?([a-zA-Z0-9]{12,16})["']?/i },
    { name: "LinkedIn Client Secret", pattern: /["']?linkedin[_\-]?client[_\-]?secret["']?\s*[:=]\s*["']?([a-zA-Z0-9]{16})["']?/i },
    { name: "Lokalise API Key", pattern: /["']?lokalise[_\-]?api[_\-]?(?:key|token)["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "Loqate API Key", pattern: /["']?loqate[_\-]?(?:api[_\-]?)?key["']?\s*[:=]\s*["']?([A-Z0-9]{6}-[A-Z0-9]{6}-[A-Z0-9]{6}-[A-Z0-9]{6})["']?/i },
    { name: "MailChimp API Key", pattern: /\b([a-f0-9]{32}-us[0-9]{1,2})\b/ },
    { name: "MailGun Private Key", pattern: /\b(key-[a-z0-9]{32})\b/ },
    { name: "Mapbox API Key (public)", pattern: /\b(pk\.eyJ1[A-Za-z0-9_\-\.]{50,})\b/ },
    { name: "Mapbox Secret Key", pattern: /\b(sk\.eyJ1[A-Za-z0-9_\-\.]{50,})\b/ },
    { name: "Azure Tenant / Client / Subscription ID", pattern: /["']?(?:tenant|subscription|client)[_\-]?id["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "Azure Client Secret", pattern: /["']?(?:azure[_\-]?)?client[_\-]?secret["']?\s*[:=]\s*["']?([A-Za-z0-9~_\.\-]{30,40})["']?/i },
    { name: "Azure SAS Token", pattern: /(?:sv|sig|se|st|spr|srt|ss|sp)=[^&\s"']{2,}&(?:sv|sig|se|st|spr|srt|ss|sp)=[^&\s"']{2,}/ },
    { name: "MS Teams Webhook", pattern: /https:\/\/[a-zA-Z0-9\-]+\.webhook\.office\.com\/webhookb2\/[a-zA-Z0-9\-@\.]+/ },
    { name: "New Relic NerdGraph Key", pattern: /\b(NRAK-[A-Z0-9]{27})\b/ },
    { name: "New Relic REST API Key", pattern: /["']?new[_\-]?relic[_\-]?(?:api[_\-]?)?(?:key|token)["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "New Relic License Key", pattern: /\b([a-f0-9]{40}NRAL)\b/ },
    { name: "NPM Token (new)", pattern: /\b(npm_[A-Za-z0-9]{36})\b/ },
    { name: "NPM Token (old)", pattern: /["']?npm[_\-]?token["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "OpsGenie API Key", pattern: /["']?opsgenie[_\-]?api[_\-]?key["']?\s*[:=]\s*["']?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "PagerDuty API Token", pattern: /["']?pagerduty[_\-]?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9_\+\-]{20})["']?/i },
    { name: "PayPal Client ID", pattern: /["']?paypal[_\-]?client[_\-]?id["']?\s*[:=]\s*["']?(A[A-Za-z0-9_\-]{79})["']?/i },
    { name: "PayPal Client Secret", pattern: /["']?paypal[_\-]?(?:client[_\-]?)?secret["']?\s*[:=]\s*["']?(E[A-Za-z0-9_\-]{79})["']?/i },
    { name: "Pendo Integration Key", pattern: /["']?pendo[_\-]?(?:integration[_\-]?|api[_\-]?)?key["']?\s*[:=]\s*["']?([a-f0-9]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "PivotalTracker API Token", pattern: /["']?pivotal[_\-]?(?:tracker[_\-]?)?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Razorpay Key ID", pattern: /\b(rzp_(?:live|test)_[A-Za-z0-9]{14})\b/ },
    { name: "Razorpay Secret", pattern: /["']?razorpay[_\-]?(?:key[_\-]?)?secret["']?\s*[:=]\s*["']?([A-Za-z0-9]{30,32})["']?/i },
    { name: "Salesforce Access Token", pattern: /["']?salesforce[_\-]?(?:access[_\-]?)?token["']?\s*[:=]\s*["']?(00D[a-zA-Z0-9]{12,15}![a-zA-Z0-9\._]{90,})["']?/i },
    { name: "SauceLabs Access Key", pattern: /["']?sauce(?:labs)?[_\-]?(?:access[_\-]?)?key["']?\s*[:=]\s*["']?([a-f0-9]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})["']?/i },
    { name: "SendGrid API Token", pattern: /\b(SG\.[A-Za-z0-9_\-]{22}\.[A-Za-z0-9_\-]{43})\b/ },
    { name: "Shodan API Key", pattern: /["']?shodan[_\-]?(?:api[_\-]?)?key["']?\s*[:=]\s*["']?([A-Za-z0-9]{32})["']?/i },
    { name: "Slack API Token", pattern: /\b(xox[baprs]\-[0-9]{10,12}\-[0-9]{10,12}\-[a-zA-Z0-9]{23,32})\b/ },
    { name: "Slack Token (generic)", pattern: /\b(xox[baprs]\-[A-Za-z0-9\-]{40,})\b/ },
    { name: "Slack Webhook URL", pattern: /https:\/\/hooks\.slack\.com\/services\/T[A-Za-z0-9_]+\/B[A-Za-z0-9_]+\/[A-Za-z0-9_]+/ },
    { name: "Sonarcloud Token", pattern: /["']?sonar(?:cloud|qube)?[_\-]?token["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "Spotify Client ID", pattern: /["']?spotify[_\-]?client[_\-]?id["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Spotify Client Secret", pattern: /["']?spotify[_\-]?client[_\-]?secret["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Square Access Token", pattern: /\b(sq0atp-[A-Za-z0-9_\-]{22})\b/ },
    { name: "Square App Secret", pattern: /\b(sq0csp-[A-Za-z0-9_\-]{43})\b/ },
    { name: "Square OAuth Token", pattern: /\b(EAAA[A-Za-z0-9_\-]{60,})\b/ },
    { name: "Stripe Live Secret Key", pattern: /\b(sk_live_[A-Za-z0-9]{24,99})\b/ },
    { name: "Stripe Live Publishable Key", pattern: /\b(pk_live_[A-Za-z0-9]{24,99})\b/ },
    { name: "Stripe Test Secret Key", pattern: /\b(sk_test_[A-Za-z0-9]{24,99})\b/ },
    { name: "Telegram Bot API Token", pattern: /\b([0-9]{8,10}:[A-Za-z0-9_\-]{35})\b/ },
    { name: "Travis CI API Token", pattern: /["']?travis[_\-]?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9_\-]{22})["']?/i },
    { name: "Twilio Account SID", pattern: /\b(AC[a-f0-9]{32})\b/ },
    { name: "Twilio Auth Token", pattern: /["']?twilio[_\-]?auth[_\-]?token["']?\s*[:=]\s*["']?([a-f0-9]{32})["']?/i },
    { name: "Twitter API Key/Secret", pattern: /["']?twitter[_\-]?(?:api[_\-]?)?(?:key|secret)["']?\s*[:=]\s*["']?([A-Za-z0-9]{35,50})["']?/i },
    { name: "Twitter Bearer Token", pattern: /\b(AAAA[A-Za-z0-9%\-_]{50,})\b/ },
    { name: "Twitter Access Token", pattern: /["']?twitter[_\-]?access[_\-]?token["']?\s*[:=]\s*["']?([0-9]{15,25}-[A-Za-z0-9]{30,40})["']?/i },
    { name: "VS App Center API Token", pattern: /["']?appcenter[_\-]?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?([a-f0-9]{40})["']?/i },
    { name: "WakaTime API Key", pattern: /\b(waka_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b/ },
    { name: "WeGlot API Key", pattern: /\b(wg_[a-z0-9]{15,30})\b/ },
    { name: "WPEngine API Key", pattern: /["']?wpengine[_\-]?(?:api[_\-]?)?(?:key|token)["']?\s*[:=]\s*["']?([A-Za-z0-9]{32,64})["']?/i },
    { name: "Zendesk API Token", pattern: /["']?zendesk[_\-]?(?:api[_\-]?)?token["']?\s*[:=]\s*["']?([A-Za-z0-9\/+]{51}=)["']?/i },
    { name: "Zendesk Access Token", pattern: /["']?zendesk[_\-]?access[_\-]?token["']?\s*[:=]\s*["']?([A-Za-z0-9_\-]{40,})["']?/i },
    { name: "Private SSH Key", pattern: /-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY( BLOCK)?-----/ },
  ];

  globalThis.SourceMapHunterSecretRules = RULES;
})();